In [3]:
import numpy as np
arr=np.array([2,3,4,6,7,9])
print(arr[0])
print(arr[2])
print(arr[4]-arr[0])
print(arr[3]+arr[2])

2
4
5
10


In [7]:
import numpy as np
arr=np.array([[2,3,5],[5,8,9]])
print(arr[1][2])
print(arr[1][0])

9
5


In [6]:
import numpy as np
arr1=np.array([3,4,7,5])
print("Array is of 1D",arr1)
arr2=np.array([[1,2,4,5],[3,4,5,6],[7,3,4,6]])
print(arr2.dtype)
print(arr2)
print(arr2.ndim)
slice=arr2[0]
print(slice)
print(arr2[0,2])

Array is of 1D [3 4 7 5]
int64
[[1 2 4 5]
 [3 4 5 6]
 [7 3 4 6]]
2
[1 2 4 5]
4
